name: Push to main CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  J1-1:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/imageBuildAndPublish.yml
    with:
      path: '.'
      packageName: 'narcissus-frontend'