name: Push to main CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  J1-1:
    uses: ./.github/workflows/imageBuildAndPublish.yml
    with:
      path: '.'
      packageName: 'narcissus-frontend'